/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accaunting_manegment_system;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author cagla
 */
public class Graph extends javax.swing.JFrame {

    /**
     * Creates new form Graph
     */
    public Graph() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Export reports");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29))
        );

        jSplitPane2.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        if (Login_Screen.usertype == "admin") {
            Admin_Screen s2 = new Admin_Screen();
            s2.setVisible(true);
        } else {
            User_Screen s1 = new User_Screen();
            s1.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
//graph
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String currentUser = Login_Screen.username;  // Username of the logged-in user
        String currentRole = Login_Screen.usertype; // Role of the logged-in user

        jPanel1.removeAll();    // Remove all components from jPanel1
        jPanel1.revalidate();   // Revalidate panel (for layout updates)
        jPanel1.repaint();      // Repaint the panel to reflect changes

        DefaultCategoryDataset dataset = new DefaultCategoryDataset(); // Create dataset for the chart

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "root")) {
            String query = "SELECT month, currency, "
                    // Calculate total amount for 'Income' transactions, else 0
                    + "SUM(CASE WHEN type = 'Income' THEN amount ELSE 0 END) AS income_total, "
                    // Calculate total amount for 'Expense' transactions, else 0
                    + "SUM(CASE WHEN type = 'Expense' THEN amount ELSE 0 END) AS expense_total "
                    // Subquery: select transactions for the user grouped by year-month
                    + "FROM (SELECT DATE_FORMAT(date, '%Y-%m') AS month, amount, type, currency, added_by FROM transactions WHERE added_by = ?) AS monthly "
                    // Group by month and currency and order results accordingly
                    + "GROUP BY month, currency ORDER BY month, currency";

            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, currentUser);  // Query only the data for the current user
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String month = rs.getString("month");       // Month info
                String currency = rs.getString("currency"); // Currency
                double income = rs.getDouble("income_total");   // Total income for the month
                double expense = rs.getDouble("expense_total"); // Total expense for the month
                double net = income - expense;                    // Net balance

                dataset.addValue(net, currency, month); // Add data to the dataset for the chart
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage()); // Show error message
        }

        String title = "Monthly Net Balance by Currency (" + currentRole + ": " + currentUser + ")"; // Chart title

        JFreeChart chart = ChartFactory.createBarChart(
                title, // Chart title
                "Month", // X-axis label
                "Amount", // Y-axis label
                dataset);       // Dataset

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(jPanel1.getSize()); // Set chart panel size to match jPanel1

        jPanel1.setLayout(new java.awt.BorderLayout());          // Set layout to BorderLayout
        jPanel1.add(chartPanel, java.awt.BorderLayout.CENTER);   // Add chart panel to center
        jPanel1.validate();                                       // Validate to update UI

    }//GEN-LAST:event_jButton1ActionPerformed

    //report   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Get the logged-in username
        String currentUser = Login_Screen.username;

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "root")) {
            // SQL query: Calculate total income and expense by month and currency
            String query = "SELECT month, currency, "
                    + "SUM(CASE WHEN type = 'Income' THEN amount ELSE 0 END) AS income_total, "
                    + "SUM(CASE WHEN type = 'Expense' THEN amount ELSE 0 END) AS expense_total "
                    + "FROM (SELECT DATE_FORMAT(date, '%Y-%m') AS month, amount, type, currency, added_by FROM transactions WHERE added_by = ?) AS monthly "
                    + "GROUP BY month, currency ORDER BY month, currency";

            // Prepare statement and set parameter
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, currentUser);
            ResultSet rs = stmt.executeQuery();

            // Use StringBuilder to create the report
            StringBuilder report = new StringBuilder();
            report.append("Monthly Income-Expense Report for ").append(currentUser).append(" (TL, USD, EUR)\n");
            report.append("============================================\n\n");

            String currentMonth = "";
            boolean hasData = false;  // Check if there is any data

            // Iterate over result set rows
            while (rs.next()) {
                hasData = true;
                String month = rs.getString("month");           // Month info
                String currency = rs.getString("currency");     // Currency
                double income = rs.getDouble("income_total");   // Total income
                double expense = rs.getDouble("expense_total"); // Total expense
                double net = income - expense;                   // Net balance

                // When month changes, add new month header to the report
                if (!month.equals(currentMonth)) {
                    currentMonth = month;
                    report.append("Month: ").append(month).append("\n");
                    report.append("----------------------------\n");
                }

                // Add income, expense, and net per currency to the report
                report.append("Currency: ").append(currency).append("\n");
                report.append("  Income : ").append(String.format("%.2f", income)).append(" ").append(currency).append("\n");
                report.append("  Expense: ").append(String.format("%.2f", expense)).append(" ").append(currency).append("\n");
                report.append("  Net    : ").append(String.format("%.2f", net)).append(" ").append(currency).append("\n\n");
            }

            // If no data found, inform the user
            if (!hasData) {
                report.append("No transaction data found for user ").append(currentUser).append(".\n");
            }

            // Open file chooser dialog
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Save Report");       // Dialog title
            fileChooser.setSelectedFile(new File("monthly_report.txt"));  // Default file name

            int userSelection = fileChooser.showSaveDialog(null);

            // If user approves, write report to file
            if (userSelection == JFileChooser.APPROVE_OPTION) {

                File fileToSave = fileChooser.getSelectedFile();

                try (FileWriter writer = new FileWriter(fileToSave)) {
                    writer.write(report.toString());  // Write report to file
                    JOptionPane.showMessageDialog(null, "File saved successfully:\n" + fileToSave.getAbsolutePath());
                } catch (IOException e) {
                    // Inform user on file write error
                    JOptionPane.showMessageDialog(null, "Error writing file:\n" + e.getMessage());
                }
            } else {
                // Inform user if save operation was canceled
                JOptionPane.showMessageDialog(null, "Save operation cancelled.");
            }

        } catch (Exception e) {

            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred during export: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
